2020-03-28 14:11:43.113 DEBUG [main]com.lza.blog.BlogApplication.logStarting:53 -Running with Spring Boot v2.1.13.RELEASE, Spring v5.1.14.RELEASE
2020-03-28 14:11:57.625 DEBUG [http-nio-1000-exec-1]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==>  Preparing: insert into bl_blog( log_url, log_params, log_status, log_message, log_method, log_time, log_result, log_ip ) values ( ?,?,?,?,?,?,?,? ) 
2020-03-28 14:11:57.653 DEBUG [http-nio-1000-exec-1]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==> Parameters: /test/textException/1(String), [1](String), 1(Integer), null, GET(String), 14(Long), {"code":20000,"msg":"操作成功!"}(String), 0:0:0:0:0:0:0:1(String)
2020-03-28 14:11:58.719 DEBUG [http-nio-1000-exec-1]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==>  Preparing: insert into bl_blog( log_url, log_params, log_status, log_message, log_method, log_time, log_result, log_ip ) values ( ?,?,?,?,?,?,?,? ) 
2020-03-28 14:11:58.721 DEBUG [http-nio-1000-exec-1]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==> Parameters: /test/textException/1(String), [1](String), 0(Integer), org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'log_url' in 'field list'
### The error may involve com.lza.blog.mapper.LogMapper.logSave-Inline
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'log_url' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'log_url' in 'field list'
	at com.lza.blog.service.impl.LogServiceImpl.logSave(LogServiceImpl.java:36)
	at com.lza.blog.aspect.RequestAspect.doAfterReturning(RequestAspect.java:92)
	at com.lza.blog.controller.TestController$$EnhancerBySpringCGLIB$$dacea2a0.testException(<generated>)
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'log_url' in 'field list'
(String), GET(String), 0(Long), {"code":20000,"msg":"操作成功!"}(String), 0:0:0:0:0:0:0:1(String)
2020-03-28 14:17:27.767 DEBUG [main]com.lza.blog.BlogApplication.logStarting:53 -Running with Spring Boot v2.1.13.RELEASE, Spring v5.1.14.RELEASE
2020-03-28 14:19:07.713 DEBUG [http-nio-1000-exec-1]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==>  Preparing: insert into bl_blog( log_url, log_params, log_status, log_message, log_method, log_time, log_result, log_ip ) values ( ?,?,?,?,?,?,?,? ) 
2020-03-28 14:19:07.951 DEBUG [http-nio-1000-exec-1]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==> Parameters: /test/textException/1(String), [1](String), 1(Integer), null, GET(String), 27560(Long), {"code":20000,"msg":"操作成功!"}(String), 127.0.0.1(String)
2020-03-28 14:19:41.289 DEBUG [http-nio-1000-exec-1]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==>  Preparing: insert into bl_blog( log_url, log_params, log_status, log_message, log_method, log_time, log_result, log_ip ) values ( ?,?,?,?,?,?,?,? ) 
2020-03-28 14:19:41.290 DEBUG [http-nio-1000-exec-1]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==> Parameters: /test/textException/1(String), [1](String), 0(Integer), org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'log_url' in 'field list'
### The error may involve com.lza.blog.mapper.LogMapper.logSave-Inline
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'log_url' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'log_url' in 'field list'
	at com.lza.blog.service.impl.LogServiceImpl.logSave(LogServiceImpl.java:36)
	at com.lza.blog.aspect.RequestAspect.doAfterReturning(RequestAspect.java:92)
	at com.lza.blog.controller.TestController$$EnhancerBySpringCGLIB$$8623207.testException(<generated>)
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'log_url' in 'field list'
(String), GET(String), 0(Long), {"code":20000,"msg":"操作成功!"}(String), 127.0.0.1(String)
2020-03-28 14:23:03.490 DEBUG [main]com.lza.blog.BlogApplication.logStarting:53 -Running with Spring Boot v2.1.13.RELEASE, Spring v5.1.14.RELEASE
2020-03-28 14:23:22.158 DEBUG [http-nio-1000-exec-1]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==>  Preparing: insert into bl_blog( log_url, log_params, log_status, log_message, log_method, log_time, log_result, log_ip ) values ( ?,?,?,?,?,?,?,? ) 
2020-03-28 14:23:22.179 DEBUG [http-nio-1000-exec-1]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==> Parameters: /test/textException/1(String), [1](String), 1(Integer), null, GET(String), 10(Long), {"code":20000,"msg":"操作成功!"}(String), 127.0.0.1(String)
2020-03-28 14:23:22.447 DEBUG [http-nio-1000-exec-1]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==>  Preparing: insert into bl_blog( log_url, log_params, log_status, log_message, log_method, log_time, log_result, log_ip ) values ( ?,?,?,?,?,?,?,? ) 
2020-03-28 14:23:22.448 DEBUG [http-nio-1000-exec-1]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==> Parameters: /test/textException/1(String), [1](String), 0(Integer), org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'log_url' in 'field list'
### The error may involve com.lza.blog.mapper.LogMapper.logSave-Inline
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'log_url' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'log_url' in 'field list'
	at com.lza.blog.service.impl.LogServiceImpl.logSave(LogServiceImpl.java:36)
	at com.lza.blog.aspect.RequestAspect.doAfterReturning(RequestAspect.java:92)
	at com.lza.blog.controller.TestController$$EnhancerBySpringCGLIB$$89cb5172.testException(<generated>)
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'log_url' in 'field list'
(String), GET(String), 0(Long), {"code":20000,"msg":"操作成功!"}(String), 127.0.0.1(String)
2020-03-28 14:27:42.461 DEBUG [http-nio-1000-exec-2]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==>  Preparing: insert into bl_blog( log_url, log_params, log_status, log_message, log_method, log_time, log_result, log_ip ) values ( ?,?,?,?,?,?,?,? ) 
2020-03-28 14:27:42.462 DEBUG [http-nio-1000-exec-2]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==> Parameters: /test/textException/23(String), [23](String), 0(Integer), com.lza.blog.exception.BlogException: 发生了异常
	at com.lza.blog.controller.TestController.testException(TestController.java:31)
	at com.lza.blog.controller.TestController$$FastClassBySpringCGLIB$$e118037c.invoke(<generated>)
	at com.lza.blog.aspect.RequestAspect.doAround(RequestAspect.java:72)
	at com.lza.blog.controller.TestController$$EnhancerBySpringCGLIB$$89cb5172.testException(<generated>)
(String), GET(String), 0(Long), null, 127.0.0.1(String)
2020-03-28 14:29:28.711 DEBUG [http-nio-1000-exec-3]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==>  Preparing: insert into bl_blog( log_url, log_params, log_status, log_message, log_method, log_time, log_result, log_ip ) values ( ?,?,?,?,?,?,?,? ) 
2020-03-28 14:29:28.712 DEBUG [http-nio-1000-exec-3]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==> Parameters: /test/textException/23(String), [23](String), 0(Integer), com.lza.blog.exception.BlogException: 发生了异常
	at com.lza.blog.controller.TestController.testException(TestController.java:31)
	at com.lza.blog.controller.TestController$$FastClassBySpringCGLIB$$e118037c.invoke(<generated>)
	at com.lza.blog.aspect.RequestAspect.doAround(RequestAspect.java:72)
	at com.lza.blog.controller.TestController$$EnhancerBySpringCGLIB$$89cb5172.testException(<generated>)
(String), GET(String), 0(Long), null, 127.0.0.1(String)
2020-03-28 14:30:45.368 DEBUG [http-nio-1000-exec-4]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==>  Preparing: insert into bl_blog( log_url, log_params, log_status, log_message, log_method, log_time, log_result, log_ip ) values ( ?,?,?,?,?,?,?,? ) 
2020-03-28 14:30:45.370 DEBUG [http-nio-1000-exec-4]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==> Parameters: /test/textException/1(String), [1](String), 1(Integer), null, GET(String), 4(Long), {"code":20000,"msg":"操作成功!"}(String), 127.0.0.1(String)
2020-03-28 14:30:45.505 DEBUG [http-nio-1000-exec-4]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==>  Preparing: insert into bl_blog( log_url, log_params, log_status, log_message, log_method, log_time, log_result, log_ip ) values ( ?,?,?,?,?,?,?,? ) 
2020-03-28 14:30:45.506 DEBUG [http-nio-1000-exec-4]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==> Parameters: /test/textException/1(String), [1](String), 0(Integer), org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'log_url' in 'field list'
### The error may involve com.lza.blog.mapper.LogMapper.logSave-Inline
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'log_url' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'log_url' in 'field list'
	at com.lza.blog.service.impl.LogServiceImpl.logSave(LogServiceImpl.java:36)
	at com.lza.blog.aspect.RequestAspect.doAfterReturning(RequestAspect.java:92)
	at com.lza.blog.controller.TestController$$EnhancerBySpringCGLIB$$89cb5172.testException(<generated>)
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'log_url' in 'field list'
(String), GET(String), 0(Long), {"code":20000,"msg":"操作成功!"}(String), 127.0.0.1(String)
2020-03-28 14:31:02.921 DEBUG [http-nio-1000-exec-5]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==>  Preparing: insert into bl_blog( log_url, log_params, log_status, log_message, log_method, log_time, log_result, log_ip ) values ( ?,?,?,?,?,?,?,? ) 
2020-03-28 14:31:02.921 DEBUG [http-nio-1000-exec-5]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==> Parameters: /test/textException/1(String), [1](String), 1(Integer), null, GET(String), 2(Long), {"code":20000,"msg":"操作成功!"}(String), 127.0.0.1(String)
2020-03-28 14:31:03.068 DEBUG [http-nio-1000-exec-5]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==>  Preparing: insert into bl_blog( log_url, log_params, log_status, log_message, log_method, log_time, log_result, log_ip ) values ( ?,?,?,?,?,?,?,? ) 
2020-03-28 14:31:03.069 DEBUG [http-nio-1000-exec-5]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==> Parameters: /test/textException/1(String), [1](String), 0(Integer), org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'log_url' in 'field list'
### The error may involve com.lza.blog.mapper.LogMapper.logSave-Inline
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'log_url' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'log_url' in 'field list'
	at com.lza.blog.service.impl.LogServiceImpl.logSave(LogServiceImpl.java:36)
	at com.lza.blog.aspect.RequestAspect.doAfterReturning(RequestAspect.java:92)
	at com.lza.blog.controller.TestController$$EnhancerBySpringCGLIB$$89cb5172.testException(<generated>)
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'log_url' in 'field list'
(String), GET(String), 0(Long), {"code":20000,"msg":"操作成功!"}(String), 127.0.0.1(String)
2020-03-28 14:33:12.333 DEBUG [main]com.lza.blog.BlogApplication.logStarting:53 -Running with Spring Boot v2.1.13.RELEASE, Spring v5.1.14.RELEASE
2020-03-28 14:33:24.974 DEBUG [http-nio-1000-exec-1]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==>  Preparing: insert into bl_log(log_url, log_params, log_status, log_message, log_method, log_time, log_result, log_ip) values (?,?,?,?,?,?,?,?) 
2020-03-28 14:33:25.007 DEBUG [http-nio-1000-exec-1]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==> Parameters: /test/textException/1(String), [1](String), 1(Integer), null, GET(String), 13(Long), {"code":20000,"msg":"操作成功!"}(String), 127.0.0.1(String)
2020-03-28 14:33:25.101 DEBUG [http-nio-1000-exec-1]com.lza.blog.mapper.LogMapper.logSave.debug:159 -<==    Updates: 1
2020-03-28 14:33:57.373 DEBUG [http-nio-1000-exec-5]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==>  Preparing: insert into bl_log(log_url, log_params, log_status, log_message, log_method, log_time, log_result, log_ip) values (?,?,?,?,?,?,?,?) 
2020-03-28 14:33:57.374 DEBUG [http-nio-1000-exec-5]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==> Parameters: /test/textException/122(String), [122](String), 0(Integer), com.lza.blog.exception.BlogException: 发生了异常
	at com.lza.blog.controller.TestController.testException(TestController.java:31)
	at com.lza.blog.controller.TestController$$FastClassBySpringCGLIB$$e118037c.invoke(<generated>)
	at com.lza.blog.aspect.RequestAspect.doAround(RequestAspect.java:72)
	at com.lza.blog.controller.TestController$$EnhancerBySpringCGLIB$$919b549.testException(<generated>)
(String), GET(String), 0(Long), null, 127.0.0.1(String)
2020-03-28 14:33:57.475 DEBUG [http-nio-1000-exec-5]com.lza.blog.mapper.LogMapper.logSave.debug:159 -<==    Updates: 1
2020-03-28 20:39:17.679 DEBUG [http-nio-1000-exec-8]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==>  Preparing: insert into bl_log(log_url, log_params, log_status, log_message, log_method, log_time, log_result, log_ip) values (?,?,?,?,?,?,?,?) 
2020-03-28 20:39:17.682 DEBUG [http-nio-1000-exec-8]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==> Parameters: /test/textException/122(String), [122](String), 0(Integer), com.lza.blog.exception.BlogException: 发生了异常
	at com.lza.blog.controller.TestController.testException(TestController.java:31)
	at com.lza.blog.controller.TestController$$FastClassBySpringCGLIB$$e118037c.invoke(<generated>)
	at com.lza.blog.aspect.RequestAspect.doAround(RequestAspect.java:72)
	at com.lza.blog.controller.TestController$$EnhancerBySpringCGLIB$$919b549.testException(<generated>)
(String), GET(String), 0(Long), null, 127.0.0.1(String)
2020-03-28 20:39:18.020 DEBUG [http-nio-1000-exec-8]com.lza.blog.mapper.LogMapper.logSave.debug:159 -<==    Updates: 1
2020-03-28 20:39:27.654 DEBUG [http-nio-1000-exec-3]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==>  Preparing: insert into bl_log(log_url, log_params, log_status, log_message, log_method, log_time, log_result, log_ip) values (?,?,?,?,?,?,?,?) 
2020-03-28 20:39:27.655 DEBUG [http-nio-1000-exec-3]com.lza.blog.mapper.LogMapper.logSave.debug:159 -==> Parameters: /test/textException/1(String), [1](String), 1(Integer), null, GET(String), 2(Long), {"code":20000,"msg":"操作成功!"}(String), 127.0.0.1(String)
2020-03-28 20:39:27.745 DEBUG [http-nio-1000-exec-3]com.lza.blog.mapper.LogMapper.logSave.debug:159 -<==    Updates: 1
